In [14]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

import pandas as pd
import numpy as np
import os

## Load dataset

In [15]:
from pathlib import Path

DATA_DIR = Path.cwd().parent.parent / "database" / "gojek" / "cleaned_gojek_data.csv"
print(f"Data directory: {DATA_DIR}")

# Load the dataset
pd.set_option('display.max_columns', None)  # Show all columns
df = pd.read_csv(DATA_DIR)
df

Data directory: /Users/miftahhadiyannoor/Documents/Gojek-Project/database/gojek/cleaned_gojek_data.csv

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,8.3,28.8,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,414000.0,23.72,4.3,4.5,Debit Card
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,1.0,Vehicle Breakdown,237000.0,5.73,4.3,4.5,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,627000.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,416000.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,737.0,48.21,4.1,4.3,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2024-11-11,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,475000.0,40.08,3.7,4.1,Uber Wallet
149996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,1093.0,21.31,4.8,5.0,UPI
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,852.0,15.93,3.9,4.4,Cash
149998,2024-10-05,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,333000.0,45.54,4.1,3.7,UPI
149999,2024-03-10,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,806.0,21.19,4.6,4.9,Credit Card

In [16]:
df.columns.tolist()

['Date',
 'Time',
 'Booking ID',
 'Booking Status',
 'Customer ID',
 'Vehicle Type',
 'Pickup Location',
 'Drop Location',
 'Avg VTAT',
 'Avg CTAT',
 'Cancelled Rides by Customer',
 'Reason for cancelling by Customer',
 'Cancelled Rides by Driver',
 'Driver Cancellation Reason',
 'Incomplete Rides',
 'Incomplete Rides Reason',
 'Booking Value',
 'Ride Distance',
 'Driver Ratings',
 'Customer Rating',
 'Payment Method']

In [17]:
# Date to datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['Time'] = pd.to_datetime(df['Time'], errors='coerce').dt.time

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  datetime64[ns]
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           150000 non-null  float64
 9   Avg CTAT                           150000 non-null  float64
 10  Cancelled Rides by Customer        150000 non-null  object
 11  Reason for cancelling by Customer  150000 non-null  object
 12  Cancelled Rides by Driver          150000 non-null  object
 13  Driver Cancellation Reason         150000 non-null  object
 14  Incomplete Rides                   150000 non-null  float64
 15  Incomplete Rides Reason            150000 non-null  object
 16  Booking Value                      150000 non-null  float64
 17  Ride Distance                      150000 non-null  float64
 18  Driver Ratings                     150000 non-null  float64
 19  Customer Rating                    150000 non-null  float64
 20  Payment Method                     150000 non-null  object
dtypes: datetime64[ns](1), float64(7), object(13)
memory usage: 24.0+ MB

## 👨‍💻 Goals project

### Build taxi tracking for similar in tracking ride
 * #### Maps tracking - Google maps
### Machine learning to ensure the project is enterprise production for better learnt
* #### Cluster fast way tracks

## Feature Engineering

In [18]:
reason_data = ['Cancelled Rides by Customer',
 'Reason for cancelling by Customer',
 'Cancelled Rides by Driver',
 'Driver Cancellation Reason',
 'Incomplete Rides',
 'Incomplete Rides Reason',
 'Driver Ratings',
 'Customer Rating',]

reason_data_df = df[reason_data]
reason_data_df.head()

,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Driver Ratings,Customer Rating
0,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,4.3,4.5
1,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,1.0,Vehicle Breakdown,4.3,4.5
2,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,4.9,4.9
3,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,4.6,5.0
4,No Reason Provided,No Reason Provided,No Reason Provided,No Reason Provided,0.0,No Reason Provided,4.1,4.3

## Define Reason Pools

In [19]:
import random

customer_cancel_reasons = [
    "Changed Mind",
    "Booked by Mistake",
    "Driver Taking Too Long",
    "Found Alternative",
    "Wrong Pickup Location",
    "No Reason Provided"
]

driver_cancel_reasons = [
    "Personal Issue",
    "Vehicle Breakdown",
    "Traffic Issue",
    "Customer Unreachable",
    "Wrong Location",
    "No Reason Provided"
]

incomplete_reasons = [
    "Vehicle Breakdown",
    "Ride Cancelled Midway",
    "Customer Issue",
    "App Error",
    "Route Problem",
    "No Reason Provided"
]

In [20]:
def generate_reason_v2(driver_rating, customer_rating):
    
    # CASE 1: Both good → clean ride
    if driver_rating >= 4.7 and customer_rating >= 4.7:
        return {
            'Cancelled Rides by Customer': "No Cancellation",
            'Reason for cancelling by Customer': "No Cancellation",
            'Cancelled Rides by Driver': "No Cancellation",
            'Driver Cancellation Reason': "No Cancellation",
            'Incomplete Rides': 0.0,
            'Incomplete Rides Reason': "No Cancellation"
        }
    
    # CASE 2: Good driver, bad customer → customer problems
    elif driver_rating >= 4.5 and customer_rating < 4.2:
        return {
            'Cancelled Rides by Customer': "Cancelled, the service is bad",
            'Reason for cancelling by Customer': random.choice(customer_cancel_reasons),
            'Cancelled Rides by Driver': "No Cancellation",
            'Driver Cancellation Reason': "No Cancellation",
            'Incomplete Rides': random.choice([0.0, 1.0]),
            'Incomplete Rides Reason': random.choice(incomplete_reasons)
        }
    
    # CASE 3: Bad driver, good customer → driver problems
    elif driver_rating < 4.2 and customer_rating >= 4.5:
        return {
            'Cancelled Rides by Customer': "No Cancellation",
            'Reason for cancelling by Customer': "No Cancellation",
            'Cancelled Rides by Driver': "Cancelled",
            'Driver Cancellation Reason': random.choice(driver_cancel_reasons),
            'Incomplete Rides': random.choice([1.0, 2.0]),
            'Incomplete Rides Reason': random.choice(incomplete_reasons)
        }
    
    # CASE 4: Both bad → chaos 😄
    elif driver_rating < 4.2 and customer_rating < 4.2:
        return {
            'Cancelled Rides by Customer': "Cancelled, the service is bad",
            'Reason for cancelling by Customer': random.choice(customer_cancel_reasons),
            'Cancelled Rides by Driver': "Cancelled",
            'Driver Cancellation Reason': random.choice(driver_cancel_reasons),
            'Incomplete Rides': random.choice([1.0, 2.0]),
            'Incomplete Rides Reason': random.choice(incomplete_reasons)
        }
    
    # CASE 5: mixed ratings → random reasons
    else:
        return {
            'Cancelled Rides by Customer': random.choice(["No Cancellation", "Cancelled"]),
            'Reason for cancelling by Customer': random.choice(customer_cancel_reasons),
            'Cancelled Rides by Driver': random.choice(["No Cancellation", "Cancelled"]),
            'Driver Cancellation Reason': random.choice(driver_cancel_reasons),
            'Incomplete Rides': random.choice([0.0, 1.0]),
            'Incomplete Rides Reason': random.choice(incomplete_reasons)
        }
    
# Generate new reason columns based on ratings
generated = df.apply(
    lambda row: generate_reason_v2(row['Driver Ratings'], row['Customer Rating']), axis=1
)
generated_df = pd.DataFrame(list(generated))

In [21]:
generated_df

,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason
0,Cancelled,Booked by Mistake,Cancelled,Customer Unreachable,0.0,Vehicle Breakdown
1,No Cancellation,No Reason Provided,Cancelled,Traffic Issue,1.0,App Error
2,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation
3,Cancelled,No Reason Provided,No Cancellation,No Reason Provided,0.0,Vehicle Breakdown
4,Cancelled,No Reason Provided,Cancelled,Personal Issue,0.0,Ride Cancelled Midway
...,...,...,...,...,...,...
149995,"Cancelled, the service is bad",Driver Taking Too Long,Cancelled,Vehicle Breakdown,1.0,Route Problem
149996,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation
149997,No Cancellation,Found Alternative,Cancelled,Vehicle Breakdown,0.0,Route Problem
149998,"Cancelled, the service is bad",Booked by Mistake,Cancelled,Wrong Location,2.0,Route Problem
149999,Cancelled,Wrong Pickup Location,No Cancellation,Personal Issue,1.0,No Reason Provided

In [22]:
# Merge back to original dataframe
df = df.drop(columns=[
    'Cancelled Rides by Customer',
    'Reason for cancelling by Customer',
    'Cancelled Rides by Driver',
    'Driver Cancellation Reason',
    'Incomplete Rides',
    'Incomplete Rides Reason'
], errors='ignore')

df = pd.concat([df, generated_df], axis=1)
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,8.3,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Booked by Mistake,Cancelled,Customer Unreachable,0.0,Vehicle Breakdown
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,237000.0,5.73,4.3,4.5,UPI,No Cancellation,No Reason Provided,Cancelled,Traffic Issue,1.0,App Error
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,627000.0,13.58,4.9,4.9,Debit Card,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,416000.0,34.02,4.6,5.0,UPI,Cancelled,No Reason Provided,No Cancellation,No Reason Provided,0.0,Vehicle Breakdown
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,737.0,48.21,4.1,4.3,UPI,Cancelled,No Reason Provided,Cancelled,Personal Issue,0.0,Ride Cancelled Midway

## Replace data -> Drop location

In [23]:
jakarta_kelurahan = [
    # Jakarta Pusat (44)
    "Gambir", "Kebon Kelapa", "Petojo Utara", "Duri Pulo", "Cideng", "Petojo Selatan",
    "Bendungan Hilir", "Karet Tengsin", "Kebon Melati", "Kebon Kacang", "Kampung Bali",
    "Petamburan", "Gelora", "Menteng", "Pegangsaan", "Cikini", "Kebon Sirih", "Gondangdia",
    "Senen", "Kwitang", "Kenari", "Paseban", "Kramat", "Bungur",
    "Cempaka Putih Timur", "Cempaka Putih Barat", "Rawasari",
    "Galur", "Tanah Tinggi", "Kampung Rawa", "Johar Baru",
    "Gunung Sahari Selatan", "Kemayoran", "Kebon Kosong", "Cempaka Baru",
    "Harapan Mulya", "Sumur Batu", "Serdang", "Utan Panjang",
    "Pasar Baru", "Gunung Sahari Utara", "Mangga Dua Selatan", "Karang Anyar", "Kartini",
 
    # Jakarta Barat (52)
    "Pinangsia", "Glodok", "Keagungan", "Krukut", "Tamansari", "Maphar", "Tangki",
    "Mangga Besar", "Tanah Sareal", "Tambora", "Duri Selatan", "Duri Utara", "Kali Anyar",
    "Pekojan", "Roa Malaka", "Angke", "Jembatan Lima", "Jembatan Besi", "Duri Kepa",
    "Wijaya Kusuma", "Tanjung Duren Utara", "Tanjung Duren Selatan", "Grogol", "Tomang",
    "Jelambar", "Jelambar Baru", "Kedaung Kali Angke", "Cengkareng Barat", "Cengkareng Timur",
    "Kapuk", "Rawa Buaya", "Duri Kosambi", "Kembangan Utara", "Kembangan Selatan",
    "Joglo", "Srengseng", "Meruya Utara", "Meruya Selatan", "Palmerah", "Kemanggisan",
    "Slipi", "Kota Bambu Utara", "Kota Bambu Selatan", "Sukabumi Utara", "Sukabumi Selatan",
    "Kelapa Dua", "Tegal Alur", "Kamal", "Pegadungan", "Kalideres", "Semanan", "Batu Ceper",
 
    # Jakarta Timur (60)
    "Matraman", "Palmeriam", "Kebon Manggis", "Pisangan Baru", "Utan Kayu Utara",
    "Utan Kayu Selatan", "Cipinang Muara", "Cipinang Besar Selatan", "Cipinang Besar Utara",
    "Cipinang Cempedak", "Jatinegara", "Rawa Bunga", "Bali Mester", "Kampung Melayu",
    "Bidara Cina", "Cawang", "Cililitan", "Kramat Jati", "Batu Ampar", "Balekambang",
    "Dukuh", "Tengah", "Gedong", "Cijantung", "Kalisari", "Pekayon",
    "Pasar Rebo", "Susukan", "Ciracas", "Rambutan", "Cibubur",
    "Makasar", "Pinang Ranti", "Cipinang Melayu", "Halim Perdana Kusuma", "Kebon Pala",
    "Penggilingan", "Cakung Barat", "Cakung Timur", "Pulo Gebang", "Ujung Menteng",
    "Rawa Terate", "Pisangan Timur", "Kayu Putih", "Rawamangun", "Jati",
    "Pondok Bambu", "Duren Sawit", "Pondok Kelapa", "Malaka Sari", "Malaka Jaya",
    "Pondok Kopi", "Lubang Buaya", "Cipayung", "Setu", "Bambu Apus",
    "Cilangkap", "Munjul", "Pondok Ranggon", "Kelapa Gading Barat", "Kelapa Gading Timur",
 
    # Jakarta Selatan (58)
    "Tebet Barat", "Tebet Timur", "Kebon Baru", "Bukit Duri", "Manggarai",
    "Manggarai Selatan", "Menteng Dalam", "Menteng Atas", "Pasar Manggis", "Guntur",
    "Setiabudi", "Karet Semanggi", "Karet Kuningan", "Kuningan Timur",
    "Pancoran", "Duren Tiga", "Kalibata", "Pengadegan", "Cikoko",
    "Ciganjur", "Jagakarsa", "Srengseng Sawah", "Tanjung Barat", "Lenteng Agung",
    "Pasar Minggu", "Kebagusan", "Ragunan", "Cilandak Timur", "Jati Padang",
    "Pejaten Timur", "Pejaten Barat", "Kemang", "Bangka", "Pela Mampang",
    "Tegal Parang", "Mampang Prapatan", "Kuningan Barat",
    "Kebayoran Lama Utara", "Kebayoran Lama Selatan", "Grogol Selatan", "Grogol Utara",
    "Pesanggrahan", "Bintaro", "Ulujami", "Cipete Selatan", "Cipete Utara",
    "Petogogan", "Melawai", "Kramat Pela", "Kebayoran Baru",
    "Gandaria Selatan", "Gandaria Utara", "Cipedak", "Cilandak Barat",
    "Lebak Bulus", "Pondok Labu", "Fatmawati", "Pondok Pinang",
 
    # Jakarta Utara (29)
    "Penjaringan", "Pejagalan", "Pluit", "Kamal Muara", "Kapuk Muara", "Tugu Utara",
    "Tugu Selatan", "Semper Barat", "Semper Timur", "Rawa Badak Utara", "Rawa Badak Selatan",
    "Lagoa", "Koja", "Tanjung Priok", "Sunter Agung", "Sunter Jaya", "Papanggo",
    "Sungai Bambu", "Kebon Bawang", "Warakas", "Pademangan Barat", "Pademangan Timur",
    "Ancol", "Kali Baru", "Cilincing", "Sukapura", "Marunda", "Rorotan", "Pulo Gadung",
]

# Remove duplicates while preserving order
jakarta_kelurahan = list(dict.fromkeys(jakarta_kelurahan))
print(f"Total unique kelurahan in Jakarta: {len(jakarta_kelurahan)}")

Total unique kelurahan in Jakarta: 244

In [24]:
# Get all unique original locations
drop_locations = df['Drop Location'].unique().tolist()
pickup_locations = df['Pickup Location'].unique().tolist()

# Create a mapping dict: each original locations -> a Jakarta kelurahan (randomly assigned)
random.seed(42)  # For reproducibility
shuffled_jakarta = jakarta_kelurahan.copy()
random.shuffle(shuffled_jakarta)

# For drop locations
drop_location_map = {}
for i, loc in enumerate(drop_locations):
    drop_location_map[loc] = shuffled_jakarta[i % len(shuffled_jakarta)]

# For pickup locations
shuffled_jakarta_pickup = jakarta_kelurahan.copy()
random.shuffle(shuffled_jakarta_pickup)

pickup_location_map = {}
for i, loc in enumerate(pickup_locations):
    pickup_location_map[loc] = shuffled_jakarta_pickup[i % len(shuffled_jakarta_pickup)]

# Apply mappings
df['Drop Location'] = df['Drop Location'].map(drop_location_map)
df['Pickup Location'] = df['Pickup Location'].map(pickup_location_map)

print("Sample of mapped drop locations:")
print(df['Drop Location'].unique()[:10])

print("\nSample of mapped pickup locations:")
print(df['Pickup Location'].unique()[:10])

Sample of mapped drop locations:
['Glodok' 'Kramat Jati' 'Kebon Kacang' 'Kota Bambu Utara'
 'Cipinang Cempedak' 'Bintaro' 'Pondok Labu' 'Penggilingan' 'Pela Mampang'
 'Pinangsia']

Sample of mapped pickup locations:
['Tanah Tinggi' 'Cipinang Melayu' 'Mangga Dua Selatan' 'Glodok'
 'Sunter Jaya' 'Semanan' 'Pesanggrahan' 'Rambutan' 'Sunter Agung'
 'Pondok Ranggon']

In [25]:
df

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Tanah Tinggi,Glodok,8.3,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Booked by Mistake,Cancelled,Customer Unreachable,0.0,Vehicle Breakdown
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Cipinang Melayu,Kramat Jati,4.9,14.0,237000.0,5.73,4.3,4.5,UPI,No Cancellation,No Reason Provided,Cancelled,Traffic Issue,1.0,App Error
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Mangga Dua Selatan,Kebon Kacang,13.4,25.8,627000.0,13.58,4.9,4.9,Debit Card,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Glodok,Kota Bambu Utara,13.1,28.5,416000.0,34.02,4.6,5.0,UPI,Cancelled,No Reason Provided,No Cancellation,No Reason Provided,0.0,Vehicle Breakdown
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Sunter Jaya,Cipinang Cempedak,5.3,19.6,737.0,48.21,4.1,4.3,UPI,Cancelled,No Reason Provided,Cancelled,Personal Issue,0.0,Ride Cancelled Midway
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2024-11-11,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,Kelapa Dua,Pulo Gebang,10.2,44.4,475000.0,40.08,3.7,4.1,Uber Wallet,"Cancelled, the service is bad",Driver Taking Too Long,Cancelled,Vehicle Breakdown,1.0,Route Problem
149996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Pinangsia,Pluit,5.1,30.8,1093.0,21.31,4.8,5.0,UPI,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Tanjung Priok,Kapuk Muara,2.7,23.4,852.0,15.93,3.9,4.4,Cash,No Cancellation,Found Alternative,Cancelled,Vehicle Breakdown,0.0,Route Problem
149998,2024-10-05,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Kebon Sirih,Cilangkap,6.9,39.6,333000.0,45.54,4.1,3.7,UPI,"Cancelled, the service is bad",Booked by Mistake,Cancelled,Wrong Location,2.0,Route Problem
149999,2024-03-10,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Jembatan Besi,Krukut,3.5,33.7,806.0,21.19,4.6,4.9,Credit Card,Cancelled,Wrong Pickup Location,No Cancellation,Personal Issue,1.0,No Reason Provided